### ISSUE TITLE
Crash in testing/balance branch on changing theme ingame

### ISSUE THREAD

**Issue by nthykier** [singularity/singularity#101]
Hi,

While playing on the `testing/balance` branch, I noticed the following crash.

```
Traceback (most recent call last):
  File "./singularity", line 23, in <module>
    import code.singularity
  File "<GIT-CHECKOUT>/code/singularity.py", line 295, in <module>
    menu_screen.show()
  File "<GIT-CHECKOUT>/code/graphics/dialog.py", line 202, in show
    result = self.handle(event)
  File "<GIT-CHECKOUT>/code/graphics/dialog.py", line 329, in handle
    return self.call_handlers(handlers, event)
  File "<GIT-CHECKOUT>/code/graphics/dialog.py", line 341, in call_handlers
    handler(event)
  File "<GIT-CHECKOUT>/code/graphics/button.py", line 154, in handle_event
    self.activate_with_sound(event)
  File "<GIT-CHECKOUT>/code/graphics/button.py", line 167, in activate_with_sound
    self.activated(event)
  File "<GIT-CHECKOUT>/code/graphics/button.py", line 195, in activated
    self.function(*self.args, **self.kwargs)
  File "<GIT-CHECKOUT>/code/screens/main_menu.py", line 105, in new_game
    dialog.call_dialog(self.map_screen, self)
  File "<GIT-CHECKOUT>/code/graphics/dialog.py", line 96, in call_dialog
    retval = dialog.show()
  File "<GIT-CHECKOUT>/code/screens/map.py", line 454, in show
    exit = dialog.call_dialog(self.menu_dialog, self)
  File "<GIT-CHECKOUT>/code/graphics/dialog.py", line 96, in call_dialog
    retval = dialog.show()
  File "<GIT-CHECKOUT>/code/graphics/dialog.py", line 188, in show
    Dialog.top.maybe_update()
  File "<GIT-CHECKOUT>/code/graphics/widget.py", line 323, in maybe_update
    self.update()
  File "<GIT-CHECKOUT>/code/graphics/widget.py", line 329, in update
    self._update()
  File "<GIT-CHECKOUT>/code/graphics/widget.py", line 361, in _update
    child._update()
  File "<GIT-CHECKOUT>/code/graphics/widget.py", line 361, in _update
    child._update()
  File "<GIT-CHECKOUT>/code/graphics/widget.py", line 338, in _update
    self.redraw()
  File "<GIT-CHECKOUT>/code/graphics/text.py", line 349, in redraw
    super(Text, self).redraw()
  File "<GIT-CHECKOUT>/code/graphics/widget.py", line 473, in redraw
    if self.background_color != g.colors["clear"]:
KeyError: 'clear'
```

So far, both crashes happened while changing the theme after playing for a while (first time, I had completed the game, the other time I was at the `Far reaches` - i.e. almost finished the game).  However, if I just start a game and immediately change the theme, it succeeds without any issue.

**Comment by Xenega** [comment]
I modified the theme system. Can you verify if it's more stable or you another error?

**Comment by nthykier** [comment]
I can still reproduce it on 3edfaef125ad85e65ac8ae4d110df35b46af662a.
The first time I can trigger it is when I get undersea labs (if that is
any help debugging the issue).

**Comment by nthykier** [comment]
I cannot reproduce it on master even after parts of testing/balance has been merged.  Given that testing/balance has been discarded in favour of smaller branches, I think we should close this issue and reopen it if the issue reappears.
