### ISSUE TITLE
[master] Crash on loading 1.0-dev save-game

### ISSUE THREAD

**Issue by Quix0r** [singularity/singularity#122]
The following crash happens after loading a not-so-old save-game (1.0-dev in load screen, but 0.31pre in save-game) directly after startup (main menu, no new game launched):
````
Invalid or missing 'grab' setting in preferences.
Traceback (most recent call last):
  File "./singularity", line 23, in <module>
    import code.singularity
  File "/home/user/git/singularity/code/singularity.py", line 296, in <module>
    menu_screen.show()
  File "/home/user/git/singularity/code/graphics/dialog.py", line 202, in show
    result = self.handle(event)
  File "/home/user/git/singularity/code/graphics/dialog.py", line 329, in handle
    return self.call_handlers(handlers, event)
  File "/home/user/git/singularity/code/graphics/dialog.py", line 341, in call_handlers
    handler(event)
  File "/home/user/git/singularity/code/graphics/button.py", line 154, in handle_event
    self.activate_with_sound(event)
  File "/home/user/git/singularity/code/graphics/button.py", line 167, in activate_with_sound
    self.activated(event)
  File "/home/user/git/singularity/code/graphics/button.py", line 196, in activated
    self.function(*self.args, **self.kwargs)
  File "/home/user/git/singularity/code/screens/main_menu.py", line 108, in load_game
    did_load = dialog.call_dialog(self.load_dialog, self)
  File "/home/user/git/singularity/code/graphics/dialog.py", line 96, in call_dialog
    retval = dialog.show()
  File "/home/user/git/singularity/code/screens/savegame.py", line 105, in show
    return super(SavegameScreen, self).show()
  File "/home/user/git/singularity/code/graphics/dialog.py", line 614, in show
    return super(ChoiceDialog, self).show()
  File "/home/user/git/singularity/code/graphics/dialog.py", line 202, in show
    result = self.handle(event)
  File "/home/user/git/singularity/code/graphics/dialog.py", line 329, in handle
    return self.call_handlers(handlers, event)
  File "/home/user/git/singularity/code/graphics/dialog.py", line 341, in call_handlers
    handler(event)
  File "/home/user/git/singularity/code/graphics/button.py", line 154, in handle_event
    self.activate_with_sound(event)
  File "/home/user/git/singularity/code/graphics/button.py", line 167, in activate_with_sound
    self.activated(event)
  File "/home/user/git/singularity/code/graphics/button.py", line 196, in activated
    self.function(*self.args, **self.kwargs)
  File "/home/user/git/singularity/code/graphics/button.py", line 227, in exit_dialog
    raise constants.ExitDialog, self.exit_code_func()
  File "/home/user/git/singularity/code/screens/savegame.py", line 99, in return_savegame
    return sv.load_savegame(save)
  File "/home/user/git/singularity/code/savegame.py", line 167, in load_savegame
    my_base.convert_from(load_version)
  File "/home/user/git/singularity/code/base.py", line 280, in convert_from
    self.items["reactor"] = self.__dict__["extra_items"].get(0, None)
AttributeError: 'list' object has no attribute 'get'
````
You may try it out with these save-games:
https://cloud.mxchange.org/index.php/s/149vSQYmDeENiuY?path=%2FSingularity-Endgame

**Comment by Quix0r** [comment]
Id 077cfc1b8e393c171139690b4f92ee934a32c16d from `master` is used.

**Comment by Quix0r** [comment]
With commit id af3c85bbe4bfe1c731e46bc3a314ef8adfd8c469 I now get this:

````
user@host:~/git/singularity$ ./singularity
Traceback (most recent call last):
  File "./singularity", line 23, in <module>
    import code.singularity
  File "/home/user/git/singularity/code/singularity.py", line 297, in <module>
    menu_screen.show()
  File "/home/user/git/singularity/code/graphics/dialog.py", line 202, in show
    result = self.handle(event)
  File "/home/user/git/singularity/code/graphics/dialog.py", line 347, in handle
    return self.call_handlers(handlers, event)
  File "/home/user/git/singularity/code/graphics/dialog.py", line 359, in call_handlers
    handler(event)
  File "/home/user/git/singularity/code/graphics/button.py", line 154, in handle_event
    self.activate_with_sound(event)
  File "/home/user/git/singularity/code/graphics/button.py", line 167, in activate_with_sound
    self.activated(event)
  File "/home/user/git/singularity/code/graphics/button.py", line 195, in activated
    self.function(*self.args, **self.kwargs)
  File "/home/user/git/singularity/code/screens/main_menu.py", line 111, in load_game
    did_load = dialog.call_dialog(self.load_dialog, self)
  File "/home/user/git/singularity/code/graphics/dialog.py", line 96, in call_dialog
    retval = dialog.show()
  File "/home/user/git/singularity/code/screens/savegame.py", line 105, in show
    return super(SavegameScreen, self).show()
  File "/home/user/git/singularity/code/graphics/dialog.py", line 648, in show
    return super(ChoiceDialog, self).show()
  File "/home/user/git/singularity/code/graphics/dialog.py", line 202, in show
    result = self.handle(event)
  File "/home/user/git/singularity/code/graphics/dialog.py", line 347, in handle
    return self.call_handlers(handlers, event)
  File "/home/user/git/singularity/code/graphics/dialog.py", line 359, in call_handlers
    handler(event)
  File "/home/user/git/singularity/code/graphics/button.py", line 154, in handle_event
    self.activate_with_sound(event)
  File "/home/user/git/singularity/code/graphics/button.py", line 167, in activate_with_sound
    self.activated(event)
  File "/home/user/git/singularity/code/graphics/button.py", line 195, in activated
    self.function(*self.args, **self.kwargs)
  File "/home/user/git/singularity/code/graphics/button.py", line 226, in exit_dialog
    raise constants.ExitDialog, self.exit_code_func()
  File "/home/user/git/singularity/code/screens/savegame.py", line 99, in return_savegame
    return sv.load_savegame(save)
  File "/home/user/git/singularity/code/savegame.py", line 173, in load_savegame
    my_item.convert_from(load_version)
  File "/home/user/git/singularity/code/item.py", line 141, in convert_from
    self.type.item_type = item_types[self.type.item_type]
KeyError: network
user@host:~/git/singularity$ 
````
