### ISSUE TITLE
reactor_type is not defined

### ISSUE THREAD

**Issue by Musickiller** [singularity/singularity#131]
# Error: 'reactor_type' is not defined
Branch: master
Latest commit 9c95809 a day ago 
OS: Win7 x64

## Recreate:
Start a New Game > Open Knowledge
or sometimes
Start a New Game > Open Knowledge > if opens, choose Diesel Generator (always error)

## Log:
```
Exception in function show at Mon Jan 28 16:12:30 2019 RTZ 2 (зима):
Traceback (most recent call last):
  File "D:\git\singularity\code\safety.py", line 47, in safe_call
    return func(*args, **kwargs)
  File "D:\git\singularity\code\graphics\dialog.py", line 202, in show
    result = self.handle(event)
  File "D:\git\singularity\code\graphics\dialog.py", line 337, in handle
    return self.call_handlers(handlers, event)
  File "D:\git\singularity\code\graphics\dialog.py", line 349, in call_handlers
    handler(event)
  File "D:\git\singularity\code\graphics\button.py", line 154, in handle_event
    self.activate_with_sound(event)
  File "D:\git\singularity\code\graphics\button.py", line 167, in activate_with_sound
    self.activated(event)
  File "D:\git\singularity\code\graphics\button.py", line 196, in activated
    self.function(*self.args, **self.kwargs)
  File "D:\git\singularity\code\graphics\button.py", line 244, in show_dialog
    raise constants.Handled, dialog.call_dialog(self.dialog, self)
  File "D:\git\singularity\code\graphics\dialog.py", line 96, in call_dialog
    retval = dialog.show()
  File "D:\git\singularity\code\screens\knowledge.py", line 210, in show
    self.set_knowledge_type(-1)
  File "D:\git\singularity\code\screens\knowledge.py", line 141, in set_knowledge_type
    self.knowledge_inner.list_pos = 0
  File "D:\git\singularity\code\graphics\widget.py", line 52, in set
    setattr(self, data_member, my_value)
  File "D:\git\singularity\code\graphics\widget.py", line 53, in set
    call_me(self, *args, **kwargs)
  File "D:\git\singularity\code\graphics\listbox.py", line 228, in _on_selection_change
    self.update_func(self.list_pos)
  File "D:\git\singularity\code\screens\knowledge.py", line 154, in set_knowledge
    self.knowledge_inner_list_key[list_pos])
  File "D:\git\singularity\code\screens\knowledge.py", line 195, in show_info
    desc_text += g.items[knowledge_key].get_quality_info()
  File "D:\git\singularity\code\item.py", line 116, in get_quality_info
    elif self.item_type.id == reactor_type:
NameError: global name 'reactor_type' is not defined
```

**Comment by Musickiller** [comment]
## Solution:
The thing seem to be fixed by changing line 116 of ./code/item.py
`elif self.item_type.id == reactor_type:`
to
`elif self.item_type.id == "reactor":`

But I have not looked through code all that much or tested extensively. It at least allows to start playing xD
