### ISSUE TITLE
Savegame crash with python3 and 0.30c savegame

### ISSUE THREAD

**Issue by nthykier** [singularity/singularity#188]
I can *only* reproduce this under python3, not python2.

```
Exception in function show at Thu Aug 22 16:35:44 2019 CEST:
Traceback (most recent call last):
  File "./singularity/code/safety.py", line 53, in safe_call
    return func(*args, **kwargs)
  File "./singularity/code/graphics/dialog.py", line 230, in show
    result = self.handle(event)
  File "./singularity/code/graphics/dialog.py", line 376, in handle
    return self.call_handlers(handlers, event)
  File "./singularity/code/graphics/dialog.py", line 391, in call_handlers
    handler(event)
  File "./singularity/code/graphics/button.py", line 155, in handle_event
    self.activate_with_sound(event)
  File "./singularity/code/graphics/button.py", line 168, in activate_with_sound
    self.activated(event)
  File "./singularity/code/graphics/button.py", line 196, in activated
    self.function(*self.args, **self.kwargs)
  File "./singularity/code/screens/map.py", line 650, in open_location
    dialog.call_dialog(self.location_dialog, self)
  File "./singularity/code/graphics/dialog.py", line 123, in call_dialog
    retval = dialog.show()
  File "./singularity/code/screens/location.py", line 167, in show
    return super(LocationScreen, self).show()
  File "./singularity/code/graphics/dialog.py", line 230, in show
    result = self.handle(event)
  File "./singularity/code/graphics/dialog.py", line 376, in handle
    return self.call_handlers(handlers, event)
  File "./singularity/code/graphics/dialog.py", line 391, in call_handlers
    handler(event)
  File "./singularity/code/graphics/button.py", line 155, in handle_event
    self.activate_with_sound(event)
  File "./singularity/code/graphics/button.py", line 168, in activate_with_sound
    self.activated(event)
  File "./singularity/code/graphics/button.py", line 196, in activated
    self.function(*self.args, **self.kwargs)
  File "./singularity/code/screens/location.py", line 223, in open_base
    dialog.call_dialog(self.base_dialog, self)
  File "./singularity/code/graphics/dialog.py", line 123, in call_dialog
    retval = dialog.show()
  File "./singularity/code/screens/base.py", line 377, in show
    return super(BaseScreen, self).show()
  File "./singularity/code/screens/base.py", line 377, in show
    return super(BaseScreen, self).show()
  File "./singularity/code/graphics/dialog.py", line 230, in show
    result = self.handle(event)
  File "./singularity/code/graphics/dialog.py", line 376, in handle
    return self.call_handlers(handlers, event)
  File "./singularity/code/graphics/dialog.py", line 391, in call_handlers
    handler(event)
  File "./singularity/code/graphics/button.py", line 155, in handle_event
    self.activate_with_sound(event)
  File "./singularity/code/graphics/button.py", line 168, in activate_with_sound
    self.activated(event)
  File "./singularity/code/graphics/button.py", line 196, in activated
    self.function(*self.args, **self.kwargs)
  File "./singularity/code/screens/map.py", line 650, in open_location
    dialog.call_dialog(self.location_dialog, self)
  File "./singularity/code/graphics/dialog.py", line 123, in call_dialog
    retval = dialog.show()
  File "./singularity/code/screens/location.py", line 167, in show
    return super(LocationScreen, self).show()
  File "./singularity/code/graphics/dialog.py", line 230, in show
    result = self.handle(event)
  File "./singularity/code/graphics/dialog.py", line 376, in handle
    return self.call_handlers(handlers, event)
  File "./singularity/code/graphics/dialog.py", line 391, in call_handlers
    handler(event)
  File "./singularity/code/graphics/button.py", line 155, in handle_event
    self.activate_with_sound(event)
  File "./singularity/code/graphics/button.py", line 168, in activate_with_sound
    self.activated(event)
  File "./singularity/code/graphics/button.py", line 196, in activated
    self.function(*self.args, **self.kwargs)
  File "./singularity/code/screens/location.py", line 223, in open_base
    dialog.call_dialog(self.base_dialog, self)
  File "./singularity/code/graphics/dialog.py", line 123, in call_dialog
    retval = dialog.show()
  File "./singularity/code/screens/base.py", line 377, in show
    return super(BaseScreen, self).show()
  File "./singularity/code/graphics/dialog.py", line 230, in show
    result = self.handle(event)
  File "./singularity/code/graphics/dialog.py", line 376, in handle
    return self.call_handlers(handlers, event)
  File "./singularity/code/graphics/dialog.py", line 391, in call_handlers
    handler(event)
  File "./singularity/code/graphics/button.py", line 155, in handle_event
    self.activate_with_sound(event)
  File "./singularity/code/graphics/button.py", line 168, in activate_with_sound
    self.activated(event)
  File "./singularity/code/graphics/button.py", line 196, in activated
    self.function(*self.args, **self.kwargs)
  File "./singularity/code/screens/base.py", line 360, in build_item
    if 0 <= result < len(build_dialog.key_list):
TypeError: '<=' not supported between instances of 'int' and 'NoneType'
```

Steps to reproduce:

 * Start the game in python3
 * Load a 0.30c savegame with a completed base but the CPU under construction (all slots used).
 * Open the base.
 * Click `Change` for the CPU (the game should now show the available CPU types).
 * Click `Cancel` (without changing anything) and you get an `A error has occurred.`-message.

**Comment by Xenega** [comment]
None < 0 is True in python2
None < 0 raise a error in python3
