### ISSUE TITLE
Crash bug

### ISSUE THREAD

**Issue by danuker** [singularity/singularity#208]
**Please include the log file**
If the "An error has occurred"-dialog mentions a log file, then please include the log file to this report.  A simple "copy-paste" of the log file contents into the report is sufficient.
----- Basic information (Please include all the data below in the bug report) ------
Please submit the crash on github: https://github.com/singularity/singularity/issues/new
Singularity version 1.0a1 (commit: singularity-1.0a1-34-g1d3d0f9)
Python version 3.7.5 (default, Oct 27 2019, 15:43:29) [GCC 9.2.1 20191022]
Exception in function show at Fri Dec 20 00:52:56 2019 EEST:
```
Traceback (most recent call last):
  File "/home/dan/Games/singularity/singularity/code/safety.py", line 62, in safe_call
    return func(*args, **kwargs)
  File "/home/dan/Games/singularity/singularity/code/graphics/dialog.py", line 230, in show
    result = self.handle(event)
  File "/home/dan/Games/singularity/singularity/code/graphics/dialog.py", line 387, in handle
    return self.call_handlers(handlers, event)
  File "/home/dan/Games/singularity/singularity/code/graphics/dialog.py", line 402, in call_handlers
    handler(event)
  File "/home/dan/Games/singularity/singularity/code/graphics/button.py", line 156, in handle_event
    self.activate_with_sound(event)
  File "/home/dan/Games/singularity/singularity/code/graphics/button.py", line 169, in activate_with_sound
    self.activated(event)
  File "/home/dan/Games/singularity/singularity/code/graphics/button.py", line 197, in activated
    self.function(*self.args, **self.kwargs)
  File "/home/dan/Games/singularity/singularity/code/graphics/button.py", line 245, in show_dialog
    raise constants.Handled(dialog.call_dialog(self.dialog, self))
  File "/home/dan/Games/singularity/singularity/code/graphics/dialog.py", line 123, in call_dialog
    retval = dialog.show()
  File "/home/dan/Games/singularity/singularity/code/screens/log.py", line 74, in show
    return super(LogScreen, self).show()
  File "/home/dan/Games/singularity/singularity/code/graphics/dialog.py", line 696, in show
    return super(ChoiceDialog, self).show()
  File "/home/dan/Games/singularity/singularity/code/graphics/dialog.py", line 216, in show
    Dialog.top.maybe_update()
  File "/home/dan/Games/singularity/singularity/code/graphics/widget.py", line 374, in maybe_update
    self.update()
  File "/home/dan/Games/singularity/singularity/code/graphics/widget.py", line 378, in update
    self.prepare_for_redraw()
  File "/home/dan/Games/singularity/singularity/code/graphics/widget.py", line 370, in prepare_for_redraw
    child.prepare_for_redraw()
  File "/home/dan/Games/singularity/singularity/code/graphics/widget.py", line 370, in prepare_for_redraw
    child.prepare_for_redraw()
  File "/home/dan/Games/singularity/singularity/code/graphics/widget.py", line 352, in prepare_for_redraw
    self.rebuild()
  File "/home/dan/Games/singularity/singularity/code/screens/log.py", line 63, in rebuild
    self.list = [self.render_log_message(message) for message in self.key_list]
  File "/home/dan/Games/singularity/singularity/code/screens/log.py", line 63, in <listcomp>
    self.list = [self.render_log_message(message) for message in self.key_list]
  File "/home/dan/Games/singularity/singularity/code/screens/log.py", line 82, in render_log_message
    log_message = message.log_line
  File "/home/dan/Games/singularity/singularity/code/logmessage.py", line 321, in log_line
    log_format = self.group_spec.discover_log or _("Base %s of type %s destroyed at location %s.")
  File "/home/dan/Games/singularity/singularity/code/logmessage.py", line 317, in group_spec
    return g.pl.groups[self._discovered_by_group_id].spec
KeyError: '0x01050000'
```
**Please include a savegame that can reproduce the issue**
If you can, please provide a savegame where it is easy to demonstrate the problem.

**To Reproduce**
I don't know how to reproduce.

**Additional context**
I can't think of any. Perhaps it has to do with the fact that I was expanding more than usual (opening many datacenters in the early game). Perhaps I opened two at the same time, but I could not reproduce (tried once).

**Comment by nthykier** [comment]
Dan Haiduc:
> **Please include the log file**
> If the "An error has occurred"-dialog mentions a log file, then please include the log file to this report.  A simple "copy-paste" of the log file contents into the report is sufficient.
> ----- Basic information (Please include all the data below in the bug report) ------
> Please submit the crash on github: https://github.com/singularity/singularity/issues/new
> Singularity version 1.0a1 (commit: singularity-1.0a1-34-g1d3d0f9)
> Python version 3.7.5 (default, Oct 27 2019, 15:43:29) [GCC 9.2.1 20191022]
> Exception in function show at Fri Dec 20 00:52:56 2019 EEST:
> ```
> [...]
> ```
> **Please include a savegame that can reproduce the issue**
> If you can, please provide a savegame where it is easy to demonstrate the problem.
> 
> **To Reproduce**
> I don't know how to reproduce.
> 
> **Additional context**
> I can't think of any. Perhaps it has to do with the fact that I was expanding more than usual (opening many datacenters in the early game). Perhaps I opened two at the same time, but I could not reproduce (tried once).
> 
> 

Hi danuker,

Thanks for reporting the bug.

I managed to reproduce the issue by:

 * Start a new game.
 * Build some bases.
 * Play until a base is discovered.
 * Check the log as a control step; This should work.
 * Save the game.
 * Load the game.
 * Check the log, which triggers the crash.


I have fixed the problem with the above in
4a91f27f61b6d7ca5f7a751dc7a82de6b80b7483 - the fix applies retroactively
to existing savegames.

Thanks,
~Niels

**Comment by nthykier** [comment]
Sorry, had to rebase - the correct commit id was c73c41bba3d3e3fdd1f5ff25afcda509fb07c56f

**Comment by danuker** [comment]
Thanks for the fix!

Indeed, it was crashing while checking the log. I am glad the stack trace was enough for you to find out! After updating it is not crashing :)
