### ISSUE TITLE
ImportError: module 'singularity.__main__' has no attribute 'main'

### ISSUE THREAD

**Issue by LW-archlinux** [singularity/singularity#272]
python 3.8.3 , archlinux 

Build master from git, https://github.com/singularity/singularity/commit/c941326ded6f47b0619544d15604c7019304d2ae

When running /usr/bin/singularity this is output :
```
$ /usr/bin/singularity
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2470, in resolve
    return functools.reduce(getattr, self.attrs, module)
AttributeError: module 'singularity.__main__' has no attribute 'main'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/singularity", line 11, in <module>
    load_entry_point('Endgame-Singularity==1.0b1', 'gui_scripts', 'singularity')()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2862, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2462, in load
    return self.resolve()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2472, in resolve
    raise ImportError(str(exc))
ImportError: module 'singularity.__main__' has no attribute 'main'
$ 
```

Starting `__main__.py` directly does show opening screen and appears to function fine.

```
$ python /usr/lib/python3.8/site-packages/singularity/__main__.py 
Singularity 1.0b1 (commit: N/A)
Running under Python 3.8.3 (default, May 17 2020, 18:15:42) [GCC 10.1.0]
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
The error-log configured as /home/panoramix/.local/share/singularity/log/error.log (lazily created when something is logged)
$ 
```

**Comment by nthykier** [comment]
@LW-archlinux Thanks for reporting this; can you check if #273 solves the problem for you?

**Comment by LW-archlinux** [comment]
Yes, downloading and applying https://github.com/singularity/singularity/pull/273.patch to master does solve the issue.
