### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'filepath'

### ISSUE THREAD

**Issue by Quix0r** [singularity/singularity#274]
**Please include the log file**
Exception in function load_savegame at Fri Jun  5 18:55:42 2020 CEST:
```
Traceback (most recent call last):
  File "/opt/git/singularity/singularity/code/screens/savegame.py", line 214, in return_savegame
    sv.load_savegame(save)
  File "/opt/git/singularity/singularity/code/savegame.py", line 290, in load_savegame
    load_path = savegame.filepath
AttributeError: 'NoneType' object has no attribute 'filepath'
````

**To Reproduce**

0. **Have NO save game**
1. Go to "Load game"
2. Click on "Load"
3. See error

**Additional context**
````
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/git/singularity/singularity/__main__.py", line 26, in <module>
    singularity.main()
  File "/opt/git/singularity/singularity/__init__.py", line 382, in main
    menu_screen.show()
  File "/opt/git/singularity/singularity/code/graphics/dialog.py", line 230, in show
    result = self.handle(event)
  File "/opt/git/singularity/singularity/code/graphics/dialog.py", line 396, in handle
    return self.call_handlers(handlers, event)
  File "/opt/git/singularity/singularity/code/graphics/dialog.py", line 411, in call_handlers
    handler(event)
  File "/opt/git/singularity/singularity/code/graphics/button.py", line 169, in handle_event
    self.activate_with_sound(event)
  File "/opt/git/singularity/singularity/code/graphics/button.py", line 186, in activate_with_sound
    self.activated(event)
  File "/opt/git/singularity/singularity/code/graphics/button.py", line 220, in activated
    self.function(*self.args, **self.kwargs)
  File "/opt/git/singularity/singularity/code/screens/main_menu.py", line 106, in load_game
    did_load = dialog.call_dialog(self.load_dialog, self)
  File "/opt/git/singularity/singularity/code/graphics/dialog.py", line 122, in call_dialog
    retval = dialog.show()
  File "/opt/git/singularity/singularity/code/screens/savegame.py", line 245, in show
    return super(SavegameScreen, self).show()
  File "/opt/git/singularity/singularity/code/graphics/dialog.py", line 682, in show
    return super(ChoiceDialog, self).show()
  File "/opt/git/singularity/singularity/code/graphics/dialog.py", line 230, in show
    result = self.handle(event)
  File "/opt/git/singularity/singularity/code/graphics/dialog.py", line 396, in handle
    return self.call_handlers(handlers, event)
  File "/opt/git/singularity/singularity/code/graphics/dialog.py", line 411, in call_handlers
    handler(event)
  File "/opt/git/singularity/singularity/code/graphics/button.py", line 169, in handle_event
    self.activate_with_sound(event)
  File "/opt/git/singularity/singularity/code/graphics/button.py", line 186, in activate_with_sound
    self.activated(event)
  File "/opt/git/singularity/singularity/code/graphics/button.py", line 220, in activated
    self.function(*self.args, **self.kwargs)
  File "/opt/git/singularity/singularity/code/graphics/button.py", line 251, in exit_dialog
    raise constants.ExitDialog(self.exit_code_func())
  File "/opt/git/singularity/singularity/code/screens/savegame.py", line 236, in return_savegame
    SAVE_NAME = save.name, \
AttributeError: 'NoneType' object has no attribute 'name'
````

**Comment by Quix0r** [comment]
It may happen when `~/.local/share/singularity/saves/` is a dead symbolic link (target was gone).
