### ISSUE TITLE
Singularity 1.0 isn't able to start up on Debian 10 (Buster)

### ISSUE THREAD

**Issue by onpon4** [singularity/singularity#293]
I decided to try out the new release, but it doesn't seem to work on my system. I'm not sure if it's a documentation issue or something else; the readme just claims that Python 3 and Pygame are needed and seems to suggest that Pygame from the Debian repo should work and looking at the documentation the blits function (where the error happened) should be available in Pygame 1.9.4, but I get an error when I run the game:

```
$ ./run_singularity.sh 
Singularity 1.00 (commit: 2ebc2f3f2059b96885416167363bde2e27ece106)
Running under Python 3.7.3 (default, Dec 20 2019, 18:57:59) [GCC 8.3.0]
pygame 1.9.4.post1
Hello from the pygame community. https://www.pygame.org/contribute.html
The error-log configured as /home/layla/.local/share/singularity/log/error.log (lazily created when something is logged)
Traceback (most recent call last):
  File "/home/layla/games/singularity-1.00/singularity/code/graphics/widget.py", line 416, in <genexpr>
    gg.screen_surface.blits(((root_surface, r, r) for r in updated_rect), doreturn=0)
IndexError: tuple index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/layla/games/singularity-1.00/singularity/__main__.py", line 26, in <module>
    main()
  File "/home/layla/games/singularity-1.00/singularity/__init__.py", line 382, in main
    menu_screen.show()
  File "/home/layla/games/singularity-1.00/singularity/code/graphics/dialog.py", line 217, in show
    Dialog.top.maybe_update()
  File "/home/layla/games/singularity-1.00/singularity/code/graphics/widget.py", line 389, in maybe_update
    self.update()
  File "/home/layla/games/singularity-1.00/singularity/code/graphics/widget.py", line 416, in update
    gg.screen_surface.blits(((root_surface, r, r) for r in updated_rect), doreturn=0)
SystemError: <built-in method blits of pygame.Surface object at 0x7f05f6976c00> returned a result with an error set
```

This is just  with the versions of Python 3 and Pygame found in the Debian repo. (Numpy 1.16.2 is installed as well, the error doesn't suggest that Numpy is the problem but I checked just in case.

🕵️

**Comment by nthykier** [comment]
Thanks for reporting the issue and sorry to hear that you had issues in the first place.

Could you please try the version at https://github.com/singularity/singularity/tree/gh-293-broken-blits-in-pg-1.9.4 to see if that fixes the issue for you?

**Comment by onpon4** [comment]
Yup it sure does! 😄 And it's no problem! I know these little thing can easily slip past your radar, it's probably happened on our projects too at some point.

🕷️

**Comment by nthykier** [comment]
Thanks for confirming. :)
