### ISSUE TITLE
pygame.error: Unsupported image format

### ISSUE THREAD

**Issue by EinstokFair** [singularity/singularity#307]
**Please include the log file**
$ singularity
Singularity 1.00 (commit: 2ebc2f3f2059b96885416167363bde2e27ece106)
Running under Python 3.9.5 (default, Jul 15 2021, 11:19:42) [GCC 10.3.0]
pygame 2.0.1 (SDL 2.0.10, Python 3.9.5)
Hello from the pygame community. https://www.pygame.org/contribute.html
The error-log configured as /home/user/.local/share/singularity/log/error.log (lazily created when something is logged)
Traceback (most recent call last):
  File "/usr/bin/singularity", line 33, in <module>
    sys.exit(load_entry_point('Endgame-Singularity==1.0', 'gui_scripts', 'singularity')())
  File "/usr/lib/python3.9/site-packages/singularity/__init__.py", line 366, in main
    gg.init_graphics_system()
  File "/usr/lib/python3.9/site-packages/singularity/code/graphics/g.py", line 118, in init_graphics_system
    theme.current.init_cache()
  File "/usr/lib/python3.9/site-packages/singularity/code/graphics/theme.py", line 173, in init_cache
    self._variants[variant].init_cache()
  File "/usr/lib/python3.9/site-packages/singularity/code/graphics/theme.py", line 222, in init_cache
    g.images[image_name] = g.load_image(image_filename)
  File "/usr/lib/python3.9/site-packages/singularity/code/graphics/g.py", line 204, in load_image
    image = pygame.image.load(filename).convert()
pygame.error: Unsupported image format

**Additional context**
the name of the file it tries to open is
/usr/lib/python3.9/site-packages/singularity/data/themes/default/images/earth.jpg

I understand that this is the problem of my linux system, not the game, but i think that maintainers of distribution will not solve this without some tips on how to do this.

**Comment by rofl0r** [comment]
works fine for me with python 2.7 based pygame <3

**Comment by EinstokFair** [comment]
«Pygame may not always be built to support all image formats. At minimum it will support uncompressed BMP. If pygame.image.get_extended() returns 'True', you should be able to load most images (including PNG, JPG and GIF).»

mine outputs True for print(pygame.image.get_extended())

**Comment by nthykier** [comment]
Hi @EinstokFair

When you start the game, do you get the menu and are you able to access the Options to change theme?

I ask because the image it fails to load is for the default theme.  I was hoping that you as a work around could try one of the other themes, but I am bit unsure what works for you at this stage.

**Comment by nthykier** [comment]
If that does not work, then a more involved attempt is to modify the `prefs.dat` file (you may have to create it) and set the `theme=vector`.  But I admit it is far from "good".

**Comment by EinstokFair** [comment]
It is possible to choose theme via command line argument at command line. But I don't know which name to try.
I am unable to get into "options" menu, because stack trace appears right after the application start.
