### ISSUE TITLE
Sway (wayland/xwayland) Crash bug

### ISSUE THREAD

**Issue by oriansj** [singularity/singularity#326]
**Please include the log file**
If the "An error has occurred"-dialog mentions a log file, then please include the log file to this report.  A simple "copy-paste" of the log file contents into the report is sufficient.

Singularity 1.00 (commit: 2ebc2f3f2059b96885416167363bde2e27ece106)
Running under Python 3.10.6 (main, Aug 10 2022, 11:19:32) [GCC 12.1.0]
pygame 2.1.2 (SDL 2.0.22, Python 3.10.6)
Hello from the pygame community. https://www.pygame.org/contribute.html
The error-log configured as /home/oriansj/.local/share/singularity/log/error.log (lazily created when something is logged)
ALSA lib pcm.c:8568:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8568:(snd_pcm_recover) underrun occurred
----- Basic information (Please include all the data below in the bug report) ------
Please submit the crash on github: https://github.com/singularity/singularity/issues/new
Fatal Python error: pygame_parachute: (pygame parachute) Segmentation Fault
Python runtime state: initialized

Current thread 0x00007f08fc035640 (most recent call first):
  <no Python frame>

Thread 0x00007f0900cf3fc0 (most recent call first):
  File "/usr/lib/python3.10/logging/__init__.py", line 1084 in flush
  File "/usr/lib/python3.10/logging/__init__.py", line 1104 in emit
  File "/usr/lib/python3.10/logging/__init__.py", line 1218 in emit
  File "/usr/lib/python3.10/logging/__init__.py", line 968 in handle
  File "/usr/lib/python3.10/logging/__init__.py", line 1696 in callHandlers
  File "/usr/lib/python3.10/logging/__init__.py", line 1634 in handle
  File "/usr/lib/python3.10/logging/__init__.py", line 1624 in _log
  File "/usr/lib/python3.10/logging/__init__.py", line 1506 in error
  File "/usr/lib/python3/dist-packages/singularity/code/safety.py", line 47 in log_error
  File "/usr/lib/python3/dist-packages/singularity/code/safety.py", line 69 in safe_call
  File "/usr/lib/python3/dist-packages/singularity/code/screens/map.py", line 580 in show
  File "/usr/lib/python3/dist-packages/singularity/code/graphics/dialog.py", line 125 in call_dialog
  File "/usr/lib/python3/dist-packages/singularity/code/screens/main_menu.py", line 104 in new_game
  File "/usr/lib/python3/dist-packages/singularity/code/graphics/button.py", line 247 in activated
  File "/usr/lib/python3/dist-packages/singularity/code/graphics/button.py", line 213 in activate_with_sound
  File "/usr/lib/python3/dist-packages/singularity/code/graphics/button.py", line 199 in handle_event
  File "/usr/lib/python3/dist-packages/singularity/code/graphics/dialog.py", line 405 in call_handlers
  File "/usr/lib/python3/dist-packages/singularity/code/graphics/dialog.py", line 390 in handle
  File "/usr/lib/python3/dist-packages/singularity/code/graphics/dialog.py", line 231 in show
  File "/usr/lib/python3/dist-packages/singularity/__init__.py", line 382 in main
  File "/usr/games/singularity", line 11 in <module>

Extension modules: pygame.base, pygame.constants, pygame.rect, pygame.rwobject, pygame.surflock, pygame.color, pygame.bufferproxy, pygame.math, pygame.surface, pygame.display, pygame.draw, pygame.event, pygame.imageext, pygame.image, pygame.joystick, pygame.key, pygame.mouse, pygame.time, pygame.mask, pygame.pixelcopy, pygame.transform, pygame.font, pygame.mixer_music, pygame.mixer, pygame.scrap, numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg.lapack_lite, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, pygame._freetype (total: 40)
Aborted
[exit code: 134]

**Please include a savegame that can reproduce the issue**
If you can, please provide a savegame where it is easy to demonstrate the problem.

Occurs on every game after approximately 200 game days of play

**To Reproduce**
If possible, please describe the steps to reproduce the behavior:
Start new game on impossible: research intrusion, then put all processing in the tool to slowly generate money, keeping only 3 stolen computers at a time.

If applicable, please add screenshots to help explain your problem.

**Additional context**
Attempting to run the game with xwayland in sway (the i3 like wayland desktop)
when switching to i3 the crashing stops entirely and I am able to play the game without issues.

**Comment by phil-hands** [comment]
I'm also seeing crashes under sway/wayland (on Debian "bookworm" 12), so rather than opening a new bug, I thought I'd just add the crash report to this one:

----- Basic information (Please include all the data below in the bug report) ------
Please submit the crash on github: https://github.com/singularity/singularity/issues/new
Singularity version 1.00
Python version 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0]
Pygame version 2.1.2
SDL version 2.26.5
Exception in function show at Sun Jul  2 23:21:18 2023 CEST:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/singularity/code/safety.py", line 64, in safe_call
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/singularity/code/graphics/dialog.py", line 231, in show
    result = self.handle(event)
             ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/singularity/code/graphics/dialog.py", line 390, in handle
    return self.call_handlers(handlers, event)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/singularity/code/graphics/dialog.py", line 405, in call_handlers
    handler(event)
  File "/usr/lib/python3/dist-packages/singularity/code/graphics/button.py", line 199, in handle_event
    self.activate_with_sound(event)
  File "/usr/lib/python3/dist-packages/singularity/code/graphics/button.py", line 213, in activate_with_sound
    self.activated(event)
  File "/usr/lib/python3/dist-packages/singularity/code/graphics/button.py", line 247, in activated
    self.function(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/singularity/code/graphics/button.py", line 295, in show_dialog
    raise constants.Handled(dialog.call_dialog(self.dialog, self))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/singularity/code/graphics/dialog.py", line 125, in call_dialog
    retval = dialog.show()
             ^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/singularity/code/screens/research.py", line 196, in show
    return super(ResearchScreen, self).show()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/singularity/code/graphics/dialog.py", line 674, in show
    return super(ChoiceDialog, self).show()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/singularity/code/graphics/dialog.py", line 230, in show
    event = pygame.event.wait()
            ^^^^^^^^^^^^^^^^^^^
pygame.error: video system not initialized
```

**Comment by nthykier** [comment]
Just to rule out known crashing bugs, could you please re-test with pygame/2.5.2 or the latest pygame-ce version?

**Comment by oriansj** [comment]
upgrading to pygame 2.5.2 appears to stop the crashing for sway.
Successfully played game to end on Impossible with only the below being written to the console.

Singularity 1.00 (commit: 2ebc2f3f2059b96885416167363bde2e27ece106)
Running under Python 3.10.7 (main, Jan  1 1970, 00:00:01) [GCC 11.3.0]
pygame 2.5.2 (SDL 2.28.5, Python 3.10.7)
Hello from the pygame community. https://www.pygame.org/contribute.html
The error-log configured as /home/oriansj/.local/share/singularity/log/error.log (lazily created when something is logged)
Warning: <singularity.code.graphics.button.Button object at 0x7f3e58214580> can't fit on its parent.
(27, 0) (63, 18) (6, 25) (63, 18)
Warning: <singularity.code.graphics.button.Button object at 0x7f3e58214760> can't fit on its parent.
(0, 0) (56, 18) (6, 25) (32, 18)
Warning: <singularity.code.graphics.button.Button object at 0x7f3e58214880> can't fit on its parent.
(0, 0) (56, 18) (6, 25) (32, 18)
Warning: <singularity.code.graphics.button.Button object at 0x7f3e582149a0> can't fit on its parent.
(0, 0) (56, 18) (6, 25) (32, 18)
Warning: <singularity.code.graphics.button.Button object at 0x7f3e58214ac0> can't fit on its parent.
(574, 0) (57, 18) (6, 25) (607, 18)
Warning: <singularity.code.graphics.button.Button object at 0x7f3e58214be0> can't fit on its parent.
(0, 0) (56, 18) (6, 25) (32, 18)
Warning: <singularity.code.graphics.button.Button object at 0x7f3e58214d00> can't fit on its parent.
(0, 0) (56, 18) (6, 25) (32, 18)
Warning: <singularity.code.graphics.button.Button object at 0x7f3e58214e20> can't fit on its parent.
(0, 0) (56, 18) (6, 25) (32, 18)
Warning: <singularity.code.graphics.button.Button object at 0x7f3e58214f40> can't fit on its parent.
(0, 0) (56, 18) (6, 25) (32, 18)
Warning: <singularity.code.graphics.button.Button object at 0x7f3e58214580> can't fit on its parent.
(1678, 0) (4835, 18) (6, 25) (30, 18)
Warning: <singularity.code.graphics.button.Button object at 0x7f3e58214760> can't fit on its parent.
(0, 0) (2088, 18) (6, 25) (70, 18)
Warning: <singularity.code.graphics.button.Button object at 0x7f3e58214880> can't fit on its parent.
(71, 0) (56, 18) (6, 25) (37, 18)
Warning: <singularity.code.graphics.button.Button object at 0x7f3e582149a0> can't fit on its parent.
(0, 0) (2088, 18) (6, 25) (70, 18)
Warning: <singularity.code.graphics.button.Button object at 0x7f3e58214ac0> can't fit on its parent.
(573, 0) (57, 18) (6, 25) (538, 18)
Warning: <singularity.code.graphics.button.Button object at 0x7f3e58214be0> can't fit on its parent.
(0, 0) (2088, 18) (6, 25) (70, 18)
Warning: <singularity.code.graphics.button.Button object at 0x7f3e58214d00> can't fit on its parent.
(0, 0) (2088, 18) (6, 25) (70, 18)
Warning: <singularity.code.graphics.button.Button object at 0x7f3e58214e20> can't fit on its parent.
(0, 0) (2088, 18) (6, 25) (70, 18)
Warning: <singularity.code.graphics.button.Button object at 0x7f3e58214f40> can't fit on its parent.
(0, 0) (2088, 18) (6, 25) (70, 18)
Warning: <singularity.code.graphics.button.Button object at 0x7f3e58214580> can't fit on its parent.
(312, 0) (63, 18) (6, 25) (63, 18)
Warning: <singularity.code.graphics.button.Button object at 0x7f3e582149a0> can't fit on its parent.
(573, 0) (57, 18) (6, 25) (346, 18)

Will be recommending that fix to the guix upstream.
