### ISSUE TITLE
cannot access local variable 'pending_value' where it is not associated with a value

### ISSUE THREAD

**Issue by hexagonrecursion** [singularity/singularity#347]
**Please include the log file**

----- Basic information (Please include all the data below in the bug report) ------
Please submit the crash on github: https://github.com/singularity/singularity/issues/new
Singularity version 1.00 (commit: v1.00-41-g083f8f6)
Python version 3.12.4 (main, Jun  7 2024, 00:00:00) [GCC 13.3.1 20240522 (Red Hat 13.3.1-1)]
Pygame version 2.6.0
SDL version 2.28.4
Exception in function show at Wed Jul 31 08:57:49 2024 MSK:
```
Traceback (most recent call last):
  File "/home/cdda/git/singularity/singularity/code/safety.py", line 69, in safe_call
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/cdda/git/singularity/singularity/code/graphics/dialog.py", line 255, in show
    result = self.handle(event)
             ^^^^^^^^^^^^^^^^^^
  File "/home/cdda/git/singularity/singularity/code/graphics/dialog.py", line 409, in handle
    return self.call_handlers(handlers, event)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cdda/git/singularity/singularity/code/graphics/dialog.py", line 424, in call_handlers
    handler(event)
  File "/home/cdda/git/singularity/singularity/code/graphics/button.py", line 215, in handle_event
    self.activate_with_sound(event)
  File "/home/cdda/git/singularity/singularity/code/graphics/button.py", line 230, in activate_with_sound
    self.activated(event)
  File "/home/cdda/git/singularity/singularity/code/graphics/button.py", line 267, in activated
    self.function(*self.args, **self.kwargs)
  File "/home/cdda/git/singularity/singularity/code/graphics/button.py", line 317, in show_dialog
    raise constants.Handled(dialog.call_dialog(self.dialog, self))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cdda/git/singularity/singularity/code/graphics/dialog.py", line 139, in call_dialog
    retval = dialog.show()
             ^^^^^^^^^^^^^
  File "/home/cdda/git/singularity/singularity/code/screens/knowledge.py", line 262, in show
    return super(KnowledgeScreen, self).show()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cdda/git/singularity/singularity/code/graphics/dialog.py", line 255, in show
    result = self.handle(event)
             ^^^^^^^^^^^^^^^^^^
  File "/home/cdda/git/singularity/singularity/code/graphics/dialog.py", line 409, in handle
    return self.call_handlers(handlers, event)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cdda/git/singularity/singularity/code/graphics/dialog.py", line 424, in call_handlers
    handler(event)
  File "/home/cdda/git/singularity/singularity/code/graphics/listbox.py", line 109, in on_click
    self.list_pos = self.safe_pos(index + self.scrollbar.scroll_pos)
    ^^^^^^^^^^^^^
  File "/home/cdda/git/singularity/singularity/code/graphics/widget.py", line 65, in set
    setattr(self, data_member, my_value)
  File "/home/cdda/git/singularity/singularity/code/graphics/widget.py", line 66, in set
    call_me(self, *args, **kwargs)
  File "/home/cdda/git/singularity/singularity/code/graphics/listbox.py", line 309, in _on_selection_change
    self.update_func(self.list_pos)
  File "/home/cdda/git/singularity/singularity/code/screens/knowledge.py", line 168, in set_knowledge
    self.show_info(
  File "/home/cdda/git/singularity/singularity/code/screens/knowledge.py", line 222, in show_info
    desc_text += g.items[knowledge_key].get_quality_info()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cdda/git/singularity/singularity/code/item.py", line 173, in get_quality_info
    pending_value *= count
    ^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'pending_value' where it is not associated with a value
```

**Please include a savegame that can reproduce the issue**

[autosave.zip](https://github.com/user-attachments/files/16436938/autosave.zip)

**To Reproduce**

1. Load the save
2. Click "knowledge"
3. Click "items"
4. Scroll down and click "quantum computer"
5. Crash

**Additional context**

**Comment by nthykier** [comment]
Thanks. Fixed in the main branch
