### ISSUE TITLE
AttributeError: 'module' object has no attribute 'font'

### ISSUE THREAD

**Issue by ElonSatoshi** [singularity/singularity#61]
Tested from AUR installation and git clone. When I start the program, it briefly displays a window and might start to play music briefly, then it crashes, printing this error message:

```
Traceback (most recent call last):
  File "singularity.py", line 23, in <module>
    import code.singularity
  File "/home/elonsatoshi/singularity/code/singularity.py", line 274, in <module>
    menu_screen = main_menu.MainMenu()
  File "/home/elonsatoshi/singularity/code/screens/main_menu.py", line 31, in __init__
    self.map_screen = map.MapScreen(self)
  File "/home/elonsatoshi/singularity/code/screens/map.py", line 194, in __init__
    self.location_dialog = location.LocationScreen(self)
  File "/home/elonsatoshi/singularity/code/screens/location.py", line 89, in __init__
    self.new_base_dialog = NewBaseDialog(self)
  File "/home/elonsatoshi/singularity/code/screens/location.py", line 243, in __init__
    base_font=gg.font[0])
AttributeError: 'module' object has no attribute 'font'
```

Operating system: Parabola Linux
Python 2.7.15
Pygame 1.9.3
Numpy 1.14.3

**Comment by Xenega** [comment]
Sorry, I forgot to commit some files to the previous merge.
Fixed.
