### ISSUE TITLE
Error at game start

### ISSUE THREAD

**Issue by PeterJust** [singularity/singularity#80]
Today I cloned the current master. Trying to run the game I got:

> # python singularity.py -s
> Traceback (most recent call last):
>   File "singularity.py", line 23, in <module>
>     import code.singularity
>   File "/path/to/singularity-master/code/singularity.py", line 34, in <module>
>     dirs.create_directories(g.force_single_dir)
>   File "/path/to/singularity-master/code/dirs.py", line 140, in create_directories
>     parent_dir = read_dirs[item["parent"]][0]
> KeyError: 'files_home'

Is it just me being inexperienced in passing arguments to python scripts, or a broken assignment?

**Comment by Xenega** [comment]
Thx
