### ISSUE TITLE
1.0-dev savegame causes exception and returns back to menu every second

### ISSUE THREAD

**Issue by Quix0r** [singularity/singularity#89]
One game from some earlier code at 23rd day throws this exception:
````
Exception in function show at Tue Jul 10 23:14:15 2018 CEST:
Traceback (most recent call last):
  File "/../singularity/code/safety.py", line 47, in safe_call
    return func(*args, **kwargs)
  File "/../singularity/code/graphics/dialog.py", line 199, in show
    Dialog.top.maybe_update()
  File "/../singularity/code/graphics/widget.py", line 301, in maybe_update
    self.update()
  File "/../singularity/code/graphics/widget.py", line 305, in update
    self.prepare_for_redraw()
  File "/../singularity/code/graphics/widget.py", line 297, in prepare_for_redraw
    child.prepare_for_redraw()
  File "/../singularity/code/graphics/widget.py", line 284, in prepare_for_redraw
    self.rebuild()
  File "/../singularity/code/screens/map.py", line 634, in rebuild
    if g.pl.display_discover == "full":
AttributeError: 'Player' object has no attribute 'display_discover'
````
An other game, only a few seconds in, shows this:
````
Exception in function show at Tue Jul 10 23:15:35 2018 CEST:
Traceback (most recent call last):
  File "/../singularity/code/safety.py", line 47, in safe_call
    return func(*args, **kwargs)
  File "/../singularity/code/graphics/dialog.py", line 202, in show
    result = self.handle(event)
  File "/../singularity/code/graphics/dialog.py", line 329, in handle
    return self.call_handlers(handlers, event)
  File "/../singularity/code/graphics/dialog.py", line 341, in call_handlers
    handler(event)
  File "/../singularity/code/screens/map.py", line 476, in on_tick
    mins_passed = g.pl.give_time(secs)
  File "/../singularity/code/player.py", line 428, in give_time
    g.map_screen.show_message(text)
  File "/../singularity/code/screens/map.py", line 336, in show_message
    dialog.call_dialog(self.message_dialog, self)
  File "/../singularity/code/graphics/dialog.py", line 96, in call_dialog
    retval = dialog.show()
  File "/../singularity/code/graphics/dialog.py", line 188, in show
    Dialog.top.maybe_update()
  File "/../singularity/code/graphics/widget.py", line 301, in maybe_update
    self.update()
  File "/../singularity/code/graphics/widget.py", line 305, in update
    self.prepare_for_redraw()
  File "/../singularity/code/graphics/widget.py", line 297, in prepare_for_redraw
    child.prepare_for_redraw()
  File "/../singularity/code/graphics/widget.py", line 284, in prepare_for_redraw
    self.rebuild()
  File "/../singularity/code/screens/map.py", line 634, in rebuild
    if g.pl.display_discover == "full":
AttributeError: 'Player' object has no attribute 'display_discover'
````
You can download that 2 games from my cloud:
https://cloud.mxchange.org/s/WFfe88mWK8rnmCB

**Comment by rofl0r** [comment]
@Xenega Xenega closed this in 86061ef 7 hours ago

i guess he fixed it with that commit

**Comment by Xenega** [comment]
Ah. Sorry. Fixed it.

**Comment by Quix0r** [comment]
The bug is still there (6fd767b4f8053c9e4bbfc9a22959e47428eec6e8). I upload my savegame better now.

**Comment by Quix0r** [comment]
And other one:
````
Traceback (most recent call last):
  File "./singularity", line 23, in <module>
    import code.singularity
  File "/home/quix0r/git/singularity/code/singularity.py", line 295, in <module>
    menu_screen.show()
  File "/home/quix0r/git/singularity/code/graphics/dialog.py", line 202, in show
    result = self.handle(event)
  File "/home/quix0r/git/singularity/code/graphics/dialog.py", line 329, in handle
    return self.call_handlers(handlers, event)
  File "/home/quix0r/git/singularity/code/graphics/dialog.py", line 341, in call_handlers
    handler(event)
  File "/home/quix0r/git/singularity/code/graphics/button.py", line 154, in handle_event
    self.activate_with_sound(event)
  File "/home/quix0r/git/singularity/code/graphics/button.py", line 167, in activate_with_sound
    self.activated(event)
  File "/home/quix0r/git/singularity/code/graphics/button.py", line 196, in activated
    self.function(*self.args, **self.kwargs)
  File "/home/quix0r/git/singularity/code/screens/main_menu.py", line 110, in load_game
    dialog.call_dialog(self.map_screen, self)
  File "/home/quix0r/git/singularity/code/graphics/dialog.py", line 96, in call_dialog
    retval = dialog.show()
  File "/home/quix0r/git/singularity/code/screens/map.py", line 460, in show
    exit = dialog.call_dialog(self.menu_dialog, self)
  File "/home/quix0r/git/singularity/code/graphics/dialog.py", line 96, in call_dialog
    retval = dialog.show()
  File "/home/quix0r/git/singularity/code/graphics/dialog.py", line 188, in show
    Dialog.top.maybe_update()
  File "/home/quix0r/git/singularity/code/graphics/widget.py", line 362, in maybe_update
    self.update()
  File "/home/quix0r/git/singularity/code/graphics/widget.py", line 366, in update
    self.prepare_for_redraw()
  File "/home/quix0r/git/singularity/code/graphics/widget.py", line 358, in prepare_for_redraw
    child.prepare_for_redraw()
  File "/home/quix0r/git/singularity/code/graphics/widget.py", line 340, in prepare_for_redraw
    self.rebuild()
  File "/home/quix0r/git/singularity/code/screens/map.py", line 654, in rebuild
    if g.pl.display_discover == "full":
AttributeError: 'Player' object has no attribute 'display_discover'
````
